── 1. Failure: Failure:1 (@tests.R#12)  ────────────────────────────────────────
Failure has been forced

── 2. Failure: Failure:2a (@tests.R#16)  ───────────────────────────────────────
Failure has been forced

── 3. Failure: Failure:2b (@tests.R#19)  ───────────────────────────────────────
FALSE isn't true.

── 4. Failure: Failure:loop (@tests.R#24)  ─────────────────────────────────────
`i` not equal to 2.
1/1 mismatches
[1] 1 - 2 == -1

── 5. Error: Error:1 (@tests.R#33)  ────────────────────────────────────────────
stop
1: stop("stop") at reporters/tests.R:33

── 6. Error: Error:3 (@tests.R#47)  ────────────────────────────────────────────
!
1: f() at reporters/tests.R:47
2: g() at reporters/tests.R:38
3: h() at reporters/tests.R:41
4: stop("!") at reporters/tests.R:44

── 7. Error: Recursion:1 (@tests.R#56)  ────────────────────────────────────────
This is deep
1: f(25) at reporters/tests.R:56
2: f(x - 1) at reporters/tests.R:54
3: f(x - 1) at reporters/tests.R:54
4: f(x - 1) at reporters/tests.R:54
5: f(x - 1) at reporters/tests.R:54
6: f(x - 1) at reporters/tests.R:54
7: f(x - 1) at reporters/tests.R:54
8: f(x - 1) at reporters/tests.R:54
9: f(x - 1) at reporters/tests.R:54
10: f(x - 1) at reporters/tests.R:54
...
18: f(x - 1) at reporters/tests.R:54
19: f(x - 1) at reporters/tests.R:54
20: f(x - 1) at reporters/tests.R:54
21: f(x - 1) at reporters/tests.R:54
22: f(x - 1) at reporters/tests.R:54
23: f(x - 1) at reporters/tests.R:54
24: f(x - 1) at reporters/tests.R:54
25: f(x - 1) at reporters/tests.R:54
26: f(x - 1) at reporters/tests.R:54
27: stop("This is deep") at reporters/tests.R:54

══ testthat results  ═══════════════════════════════════════════════════════════
[ OK: 5 | SKIPPED: 3 | WARNINGS: 3 | FAILED: 7 ]
1. Failure: Failure:1 (@tests.R#12) 
2. Failure: Failure:2a (@tests.R#16) 
3. Failure: Failure:2b (@tests.R#19) 
4. Failure: Failure:loop (@tests.R#24) 
5. Error: Error:1 (@tests.R#33) 
6. Error: Error:3 (@tests.R#47) 
7. Error: Recursion:1 (@tests.R#56) 

